// This file is generated by rust-protobuf 2.28.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `storage.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_28_0;

#[derive(PartialEq,Clone,Default)]
pub struct CharacterMetadata {
    // message fields
    pub uuid: ::std::string::String,
    pub owner: ::std::string::String,
    // message oneof groups
    pub _latest_revision: ::std::option::Option<CharacterMetadata_oneof__latest_revision>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a CharacterMetadata {
    fn default() -> &'a CharacterMetadata {
        <CharacterMetadata as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
pub enum CharacterMetadata_oneof__latest_revision {
    latest_revision(u64),
}

impl CharacterMetadata {
    pub fn new() -> CharacterMetadata {
        ::std::default::Default::default()
    }

    // string uuid = 1;


    pub fn get_uuid(&self) -> &str {
        &self.uuid
    }
    pub fn clear_uuid(&mut self) {
        self.uuid.clear();
    }

    // Param is passed by value, moved
    pub fn set_uuid(&mut self, v: ::std::string::String) {
        self.uuid = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_uuid(&mut self) -> &mut ::std::string::String {
        &mut self.uuid
    }

    // Take field
    pub fn take_uuid(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.uuid, ::std::string::String::new())
    }

    // string owner = 2;


    pub fn get_owner(&self) -> &str {
        &self.owner
    }
    pub fn clear_owner(&mut self) {
        self.owner.clear();
    }

    // Param is passed by value, moved
    pub fn set_owner(&mut self, v: ::std::string::String) {
        self.owner = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_owner(&mut self) -> &mut ::std::string::String {
        &mut self.owner
    }

    // Take field
    pub fn take_owner(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.owner, ::std::string::String::new())
    }

    // uint64 latest_revision = 3;


    pub fn get_latest_revision(&self) -> u64 {
        match self._latest_revision {
            ::std::option::Option::Some(CharacterMetadata_oneof__latest_revision::latest_revision(v)) => v,
            _ => 0,
        }
    }
    pub fn clear_latest_revision(&mut self) {
        self._latest_revision = ::std::option::Option::None;
    }

    pub fn has_latest_revision(&self) -> bool {
        match self._latest_revision {
            ::std::option::Option::Some(CharacterMetadata_oneof__latest_revision::latest_revision(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_latest_revision(&mut self, v: u64) {
        self._latest_revision = ::std::option::Option::Some(CharacterMetadata_oneof__latest_revision::latest_revision(v))
    }
}

impl ::protobuf::Message for CharacterMetadata {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.uuid)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.owner)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self._latest_revision = ::std::option::Option::Some(CharacterMetadata_oneof__latest_revision::latest_revision(is.read_uint64()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.uuid.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.uuid);
        }
        if !self.owner.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.owner);
        }
        if let ::std::option::Option::Some(ref v) = self._latest_revision {
            match v {
                &CharacterMetadata_oneof__latest_revision::latest_revision(v) => {
                    my_size += ::protobuf::rt::value_size(3, v, ::protobuf::wire_format::WireTypeVarint);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.uuid.is_empty() {
            os.write_string(1, &self.uuid)?;
        }
        if !self.owner.is_empty() {
            os.write_string(2, &self.owner)?;
        }
        if let ::std::option::Option::Some(ref v) = self._latest_revision {
            match v {
                &CharacterMetadata_oneof__latest_revision::latest_revision(v) => {
                    os.write_uint64(3, v)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> CharacterMetadata {
        CharacterMetadata::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "uuid",
                |m: &CharacterMetadata| { &m.uuid },
                |m: &mut CharacterMetadata| { &mut m.uuid },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "owner",
                |m: &CharacterMetadata| { &m.owner },
                |m: &mut CharacterMetadata| { &mut m.owner },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_u64_accessor::<_>(
                "latest_revision",
                CharacterMetadata::has_latest_revision,
                CharacterMetadata::get_latest_revision,
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<CharacterMetadata>(
                "CharacterMetadata",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static CharacterMetadata {
        static instance: ::protobuf::rt::LazyV2<CharacterMetadata> = ::protobuf::rt::LazyV2::INIT;
        instance.get(CharacterMetadata::new)
    }
}

impl ::protobuf::Clear for CharacterMetadata {
    fn clear(&mut self) {
        self.uuid.clear();
        self.owner.clear();
        self._latest_revision = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for CharacterMetadata {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CharacterMetadata {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\rstorage.proto\x12\x07storage\"\x7f\n\x11CharacterMetadata\x12\x12\n\
    \x04uuid\x18\x01\x20\x01(\tR\x04uuid\x12\x14\n\x05owner\x18\x02\x20\x01(\
    \tR\x05owner\x12,\n\x0flatest_revision\x18\x03\x20\x01(\x04H\0R\x0elates\
    tRevision\x88\x01\x01B\x12\n\x10_latest_revisionJ\xe7\x01\n\x06\x12\x04\
    \0\0\t\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x02\0\
    \x10\n\n\n\x02\x04\0\x12\x04\x04\0\t\x01\n\n\n\x03\x04\0\x01\x12\x03\x04\
    \x08\x19\n\x0b\n\x04\x04\0\x02\0\x12\x03\x05\x02\x12\n\x0c\n\x05\x04\0\
    \x02\0\x05\x12\x03\x05\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x05\t\
    \r\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x05\x10\x11\n\x0b\n\x04\x04\0\x02\
    \x01\x12\x03\x06\x02\x13\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x06\x02\
    \x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x06\t\x0e\n\x0c\n\x05\x04\0\
    \x02\x01\x03\x12\x03\x06\x11\x12\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x08\
    \x02&\n\x0c\n\x05\x04\0\x02\x02\x04\x12\x03\x08\x02\n\n\x0c\n\x05\x04\0\
    \x02\x02\x05\x12\x03\x08\x0b\x11\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\
    \x08\x12!\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x08$%b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
